name: pinns-journey
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # Remove if no GPU
  - numpy
  - matplotlib
  - scipy
  - pandas
  - jupyter
  - ipykernel
  - tqdm
  - pytest
  - pip
  - pip:
    - wandb
    - tensorboard
    - torchinfo
    - sphinx
    - sphinx-rtd-theme